### ISSUE TITLE
New release with support for RM4C mini (product ID 0x520D)?

### ISSUE THREAD

**Issue by mt0321** [mjg59/python-broadlink#705] opened 2022-08-02 04:44 UTC
Hello,

Could we get a new release supporting the Broadlink Bestcon RM4C mini with product ID 0x520D? 

Support was [merged in to the new_product_ids branch](https://github.com/mjg59/python-broadlink/pull/694) in June thanks to [titusthefox04](https://github.com/titusthefox04), but it's [not in the main branch](https://github.com/mjg59/python-broadlink/compare/master...new_product_ids) and also [not available via Home Assistant](https://community.home-assistant.io/t/broadlink-rm4c-mini-not-supported/439216/9), presumably because the last release was [0.18.2 in May](https://github.com/mjg59/python-broadlink/releases/tag/0.18.2).

Let me know if I can help. Thank you!

**Comment by seb5594** [comment] 2022-08-08 16:10
Would be very nice if this device could get be added into the main branch :)

**Comment by guieiras** [comment] 2022-08-08 19:16
Can't wait for this release to. I bought 3 RM4C mini with product ID 0x520D and would love to have native support.
---

Tip: If someone wants to support new Product IDs right now, [patching manually the Home Assistant instance](https://github.com/mjg59/python-broadlink/pull/476#issuecomment-741993771) can be a solution.

1) Open Home Assistant and install "SSH & Web Terminal" add-on
2) Disable Protection mode
3) Connect to the Home Assistant instance via SSH:

```bash
ssh USER@IPADDRESS
docker exec -it homeassistant /bin/bash
cd /./usr/local/lib/python3.10/site-packages/broadlink
wget -O __init__.py https://raw.githubusercontent.com/mjg59/python-broadlink/new_product_ids/broadlink/__init__.py
```

4) Restart the server.

**Comment by OGB1952** [comment] 2022-08-10 15:18
I'm another one that has just bought a few of these newer RM4C Minis and have run into the same issue, so if there is an easy way to patch HA to recognise these product ID 0x520D RM4C Minis I would be grateful for any tips (I am definitely a novice!).

**Comment by guieiras** [comment] 2022-08-10 16:43
@OGB1952 You can try the steps on my comment above. After step 4 (restart the server), your HA should be able to recognize the RM4C using the native Broadlink integration.

**Comment by OGB1952** [comment] 2022-08-11 10:10
Many thanks, but try as I might I cannot find the location of the broadlink directory, or even the location of the Python directory.  I'm running HA on a Raspberry Pi using the standard HAOS installation, so not using Docker.  I've hunted high and low through the file system to try and locate where the file containing the definitions may be lurking to no avail.   This is all that is in the /usr/local/lib directory:

```
[core-ssh /]$ cd /./usr/local/lib
[core-ssh lib]$ ls
libjemalloc.a      libjemalloc.so     libjemalloc.so.2   libjemalloc_pic.a  pkgconfig

```

It's a bit frustrating, as if I've understood things correctly it looks like all the needs to be done is to add a line in a file to define the 0x520D product ID.

**Comment by iron-2** [comment] 2022-08-22 18:26
Just got mine RM4C mini and have the same issue. Hopefully this is fixed soon.

**Comment by seb5594** [comment] 2022-08-26 06:42
> Can't wait for this release to. I bought 3 RM4C mini with product ID 0x520D and would love to have native support.
> 
> ---
> 
> Tip: If someone wants to support new Product IDs right now, [patching manually the Home Assistant instance](https://github.com/mjg59/python-broadlink/pull/476#issuecomment-741993771) can be a solution.
> 
> 1) Open Home Assistant and install "SSH & Web Terminal" add-on
> 2) Disable Protection mode
> 3) Connect to the Home Assistant instance using SSH:
> 
> ```bash
> ssh USER@IPADDRESS
> docker exec -it homeassistant /bin/bash
> cd /./usr/local/lib/python3.10/site-packages/broadlink
> wget -O __init__.py https://raw.githubusercontent.com/mjg59/python-broadlink/new_product_ids/broadlink/__init__.py
> ```
> 
> 4) Restart the server.

This does not work anymore since latest HassOS update. The python packages seems to have a new location. Do you know the new location?

**Comment by OGB1952** [comment] 2022-08-26 08:15
I've spent a fair bit of time trying to find where the packages have moved to with no luck, I'm afraid.  It's irritating knowing that a simple file edit will probably fix this, but not being able to find where that file now is.

**Comment by iron-2** [comment] 2022-08-26 18:42
Where can I leave a post so that the devs get a message on this issue??

**Comment by guieiras** [comment] 2022-08-26 23:14
I feel sorry that you couldn't find the files with the guide on my comments above, but I’ll try to be more specific and I hope you should be able to manually patch your instance.

1) Use the Add-on from *Home Assistant Community Add-ons*, not from *Official Add-ons*
![72949D4B-7AC0-43C0-A636-4EE3CC277B00](https://user-images.githubusercontent.com/16104013/187001144-e46eac78-2afc-4a7b-8ed2-a48dc046cbbe.png)

2) It’s very important that you disable **Protection Mode**
3) Connect to your instance using SSH. That’s what you should see when instance is connected
![F2A4C9B8-3893-423A-A0C1-CD675672C96F](https://user-images.githubusercontent.com/16104013/187001622-4135f0dd-eb22-49cf-8246-fd755256cb53.jpeg)
4) Follow the steps 3-4, the “docker” command should work no matter what is your installation.

**Comment by KennyHec** [comment] 2022-09-14 15:29
For those having problems with python dir not being found, use this instead in the terminal. This has always worked for me. 

```
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/mjg59/python-broadlink.git@new_product_ids --force-reinstall --no-deps
```

**Comment by FlameSoulis** [comment] 2022-09-26 03:08
I'm reporting that the above instructions are incorrect. I have a core installation on a virtual machine, and I'm noticing that python is entirely missing. Perhaps this is the cause of all the problems?

In addition, the docker command doesn't work either because the command doesn't exist.

![image](https://user-images.githubusercontent.com/6835457/192186244-9014e65f-4d6c-4258-9825-d7c11bdd38e4.png)

**Comment by domoaligato** [comment] 2022-10-12 19:55
the workaround works for me on unraid in docker.

**Comment by simonbrunton** [comment] 2022-10-21 00:36
RM4C mini is still not supported in 2022.10.5

**Comment by ALEXOTANO** [comment] 2022-10-30 21:06
I can't believe this haven't been solved, it is already merged to a branch and super-tested by the community, you should merge it already to main branch.

**Comment by RandyLevensalor** [comment] 2022-11-02 03:32
@felipediel @mjg59 Is there anything we can do to help get a new release published?  This patch has been merged and it would be great to have it included it included without needing to mod home assistant.

**Comment by lobbie1978** [comment] 2022-11-07 16:41
Same here. Command line does not work: "command not found".
I have been waiting for support for this device for months now. Please merge the branch to main asap!

**Comment by KennyHec** [comment] 2022-11-07 18:54
> Same here. Command line does not work: "command not found".
> I have been waiting for support for this device for months now. Please merge the branch to main asap!

What command are u (trying to) using?

**Comment by bisquit2003** [comment] 2022-11-08 08:01
> Same here. Command line does not work: "command not found". I have been waiting for support for this device for months now. Please merge the branch to main asap!

check addon, you need WEB terminal, not terminal

**Comment by Druidblack** [comment] 2022-11-13 05:09
The above method no longer works.

`docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/mjg59/python-broadlink.git@new_product_ids --force-reinstall --no-deps`
P.S. When will the normal support for these remotes be added?

**Closed** 2022-11-20 20:08 UTC
